-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-14 22:06:10 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE country (
    country VARCHAR2(100) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country );

CREATE TABLE country_dystopia_residual (
    dystopia_residual  FLOAT(100),
    datetime             DATE NOT NULL,
    country_country    VARCHAR2(100) NOT NULL
);

ALTER TABLE country_dystopia_residual ADD CONSTRAINT country_dystopia_residual_pk PRIMARY KEY ( datetime,
                                                                                                country_country );

CREATE TABLE country_economy (
    economy          FLOAT(100),
    datetime           DATE NOT NULL,
    country_country  VARCHAR2(100) NOT NULL
);

ALTER TABLE country_economy ADD CONSTRAINT country_economy_pk PRIMARY KEY ( datetime,
                                                                            country_country );


CREATE TABLE person (
    name VARCHAR2(100) NOT NULL
);

ALTER TABLE person ADD CONSTRAINT person_pk PRIMARY KEY ( name );

CREATE TABLE region (
    region VARCHAR2(200) NOT NULL
);

ALTER TABLE region ADD CONSTRAINT region_pk PRIMARY KEY ( region );

CREATE TABLE tourist (
    datetime           DATE NOT NULL,
    country_country  VARCHAR2(100) NOT NULL,
    person_name      VARCHAR2(100) NOT NULL
);

ALTER TABLE tourist
    ADD CONSTRAINT tourist_pk PRIMARY KEY ( datetime,
                                            country_country,
                                            person_name );

ALTER TABLE country_dystopia_residual
    ADD CONSTRAINT country_dyst_res_country_fk FOREIGN KEY ( country_country )
        REFERENCES country ( country );

ALTER TABLE country_economy
    ADD CONSTRAINT country_economy_country_fk FOREIGN KEY ( country_country )
        REFERENCES country ( country );



ALTER TABLE country_region
    ADD CONSTRAINT country_region_country_fk FOREIGN KEY ( country_country )
        REFERENCES country ( country );

ALTER TABLE country_region
    ADD CONSTRAINT country_region_region_fk FOREIGN KEY ( region_region )
        REFERENCES region ( region );

ALTER TABLE tourist
    ADD CONSTRAINT tourist_country_fk FOREIGN KEY ( country_country )
        REFERENCES country ( country );

ALTER TABLE tourist
    ADD CONSTRAINT tourist_person_fk FOREIGN KEY ( person_name )
        REFERENCES person ( name );



