-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-29 20:18:52 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
--DROP TABLE countryregion;
--DROP TABLE countryhappinesscore;
--DROP TABLE region;

CREATE TABLE countryregion (
    country        VARCHAR2(100) NOT NULL,
    region         VARCHAR2(200)
);

ALTER TABLE countryregion ADD CONSTRAINT countryregion_pk PRIMARY KEY ( country );

CREATE TABLE countryhappinesscore (
    country                     VARCHAR2(100) NOT NULL,
    economy                     FLOAT(100),
    family                      FLOAT(100),
    health                      FLOAT(100),
    freedom                     FLOAT(100),
    trust                       FLOAT(100),
    generosity                  FLOAT(100),
    dystopia_residual           FLOAT(100)
);

ALTER TABLE countryhappinesscore
    ADD CONSTRAINT countryhappinesscore_pk PRIMARY KEY ( country );

CREATE TABLE region (
    region VARCHAR2(200) NOT NULL
);

ALTER TABLE region ADD CONSTRAINT region_pk PRIMARY KEY ( region );

ALTER TABLE countryregion
    ADD CONSTRAINT countryregion_region_fk FOREIGN KEY ( region )
        REFERENCES region ( region );


ALTER TABLE countryhappinesscore
    ADD CONSTRAINT countryHS_contryregion_fk FOREIGN KEY (country)
        REFERENCES countryregion ( country );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             1
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
